- name: Modify daemon.json
  copy:
    dest: /etc/docker/daemon.json
    src: files/daemon.json

- name: Restart docker service
  systemd:
    state: restarted
    name: docker

- name: Import k8s GPG key
  shell:
    cmd: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/k8s-archive-keyring.gpg
    creates: /usr/share/keyrings/k8s-archive-keyring.gpg

- name: Add k8s apt repository
  shell:
    cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/k8s-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
      | tee /etc/apt/sources.list.d/k8s.list > /dev/null
    creates: /etc/apt/sources.list.d/k8s.list

- name: Install k8s packages
  apt:
    pkg:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
    state: latest
    update_cache: yes

- name: Enable services
  systemd:
    enabled: yes
    name: kubelet
