- hosts: local
  become: yes
  roles:
    - kvm
  tasks:
    - name: Setup virtual network
      include_role:
        name: create-virtual-network
      vars:
        network_name: "{{ k8s_network.name }}"
        ip_address: "{{ k8s_network.ip_address }}"
        netmask: "{{ k8s_network.netmask }}"
        dhcp_start: "{{ k8s_network.dhcp_start }}"
        dhcp_end: "{{ k8s_network.dhcp_end }}"

    - name: Setup VMs
      include_role:
        name: create-virtual-machine
      vars:
        os_variant: "{{ vm.os_variant }}"
        ssh_public_key: "{{ ansible_ssh_public_key }}"
        libvirt_images_folder: "{{ libvirt.images_folder }}"
        base_image_name: "{{ vm.base_image_name }}"
        base_image_url: "{{ vm.base_image_url }}"
        network_name: "{{ k8s_network.name }}"
      with_inventory_hostnames:
        - vms
