- hosts: local
  become: yes
  tasks:
    - name: Install KVM packages
      apt:
        pkg:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
        state: latest

    - name: Add user '{{ ansible_user }}' to libvirt and kvm groups
      user:
        name: '{{ ansible_user }}'
        groups:
          - libvirt
          - kvm
        append: yes

    - name: Enable and start a libvirtd unit
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: yes
