- hosts: local
  become: yes
  tasks:
    - name: Start VMs
      community.libvirt.virt:
        name: "{{ item }}"
        state: running
      with_inventory_hostnames:
        - vms

    - name: Find VMs IPs
      shell:
        executable: bash
        cmd:
          while [ "$(virsh net-dhcp-leases {{ net_name }} | grep {{ item }} >/dev/null 2>&1 && echo 1 || echo 0)" == "0" ]; do
            sleep 5;
          done;
          virsh net-dhcp-leases {{ net_name }} | grep {{ item }} | awk '{ print $5; }' | cut -d/ -f1
      with_inventory_hostnames:
        - vms
      register: vms_ips_raw

    - name: Find VMs IPs | Populate VMs IPs map
      set_fact:
        vms_ips: "{{ vms_ips|default({}) | combine({ item.item: item.stdout }) }}"
      with_items: "{{ vms_ips_raw.results }}"

    - name: Find VMs IPs | Register VMs in inventory
      add_host:
        name: "{{ item }}"
      args:
        ansible_host: "{{ vms_ips[item] }}"
      with_inventory_hostnames:
        - vms

    - name: Find VMs IPs | Add /etc/hosts entries
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ vms_ips[item] }} {{item}}"
        state: present
      with_inventory_hostnames:
        - vms

    - name: Wait for SSH port open
      wait_for:
        host: "{{ vms_ips[item] }}"
        port: 22
      with_inventory_hostnames:
        - vms
