- hosts: k8s_management_nodes
  become: yes
  tasks:
    - name: Setup worker nodes | Print join command
      shell:
        cmd: kubeadm token create --print-join-command
      register: k8s_cluster_join_command_raw

    - name: Setup worker nodes | Extract join command
      set_fact:
        k8s_cluster_join_command: "{{ k8s_cluster_join_command_raw.stdout }}"

- hosts: k8s_worker_nodes
  become: yes
  tasks:
    - name: Setup worker nodes | kubeadm join
      shell:
        cmd: "{{ hostvars[groups['k8s_management_nodes'][0]]['k8s_cluster_join_command'] }}"
        creates: /etc/kubernetes/kubelet.conf
